name: "CodeBeaver Test Generator"
description: "Automatically generate unit tests for your pull requests using CodeBeaver"
author: "CodeBeaver"

branding:
  icon: "check-circle"
  color: "blue"

inputs:
  api-key:
    description: "CodeBeaver API Key"
    required: true
  repository:
    description: "The repository in owner/repo format"
    required: false
    default: ${{ github.repository }}
  pr-number:
    description: "Pull request number"
    required: false
    default: ${{ github.event.pull_request && github.event.pull_request.number || '' }}
  commit_sha:
    description: "Commit SHA to analyze"
    required: false
    default: ${{ github.event.pull_request && github.event.pull_request.head.sha || github.sha }}
  action-type:
    required: false
    description: "Type of action to perform"
    default: "analyze-and-generate"

runs:
  using: "node20"
  main: "dist/index.js"
